language: node_js
node_js:
 - 'stable' 

services:
  - docker

script:
  # - docker-compose -f docker-compose.dev.yml run app sh -c "npm test && npm run lint"
  - docker-compose -f docker-compose.dev.yml run app sh -c "npm test"

