version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./src/:/home/user/src/
      - /home/user/src/node_modules
    command: >
      sh -c "npm run dev"
    environment:
      - HOST:${HOST}
      - PORT:${PORT}
