version: "3"

services:
  # Development service
  app:
    container_name: 'bookish_node'
    build:
      context: .
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - ./src/:/home/user/src/
      - /home/user/src/node_modules
    command: >
      sh -c "npm run dev"
    environment:
      - HOST=${HOST}
      - PORT=${PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_URI=${DB_URI}
    depends_on:
      - db

  db:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MONGO_INITDB_USERNAME=${DB_USER}
      - MONGO_INITDB_PASSWORD=${DB_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_NAME}
    ports:
      - '${DB_PORT}:27017'

    volumes:
      # Make data persist on local folder named ./mongo-volume
      - ${DB_DATA}:/data/db
      # Copy the database initialization script
      - ${DB_INIT}:/docker-entrypoint-initdb.d/init-mongo.sh 
        # Map mongo config file to /etc/mongo
      - ${DB_CONFIG}:/etc/mongo/
    # Specify config file
    command: ["-f", "/etc/mongo/mongod.conf"]
