version: "3"

services:
  # Development service
  app:
    container_name: 'bookish_node_dev'
    build:
      context: ./src/
    ports:
      - "${PORT}:8000"
    volumes:
      - ./src/:/home/user/src/
      - /home/user/src/node_modules
    command: >
      sh -c "npm run dev"
    environment:
      - HOST=${HOST}
      - PORT=${PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_URI=${DB_URI}
    depends_on:
      - db

  db:
    container_name: "mongodb"
    image: mongo:latest
    hostname: mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DB_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MONGO_INITDB_USERNAME=${DB_USER}
      - MONGO_INITDB_PASSWORD=${DB_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_NAME}
    ports:
      - '${DB_PORT}:27017'
    volumes:
      # Map mongo config file to /etc/mongo
      - ${DB_CONFIG}:/etc/mongo/
      # Copy the database initialization script
      - ${DB_INIT}:/docker-entrypoint-initdb.d/
      # Make data persist on local folder named ./mongo-volume
      - ${DB_DATA}:/data/db
    # Specify config file
    command: ["-f", "/etc/mongo/mongod.conf"]

  # Api doc
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: 'api_swagger'
    ports:
      - "${SWAGGER_PORT}:8080"
    volumes:
      - ${SWAGGER_DIR}:/usr/share/nginx/html/doc
    environment:
      API_URL: ${SWAGGER_API_URL}

  redoc:
    image: nginx
    container_name: 'api_redoc'
    ports:
      - "${REDOC_PORT}:80"
    volumes:
      - ${REDOC_SRC}:/usr/share/nginx/html
      - ${REDOC_CONF}:/etc/nginx/nginx.conf
