version: "3"

secrets:
  DB_ROOT_USER:
    file: ./config/.secrets/db_root_user
  DB_ROOT_PASSWORD:
    file: ./config/.secrets/db_root_passwd
  DB_PASSWORD:
    file: ./config/.secrets/db_passwd
  DB_USER:
    file: ./config/.secrets/db_user
  TOKEN_SECRET:
    file: ./config/.secrets/token_secret
  DB_URI:
    file: ./config/.secrets/db_uri
  DB_NAME:
    file: ./config/.secrets/db_name

services:
  # Development service
  app:
    container_name: 'bookish_node'
    build:
      context: ./src/
    ports:
      - "${PORT}:8000"
    volumes:
      - ./src/:/home/user/src/
      - /home/user/src/node_modules
    command: >
      sh -c "npm start"
    environment:
      - HOST=${HOST}
      - PORT=${PORT}
      - TOKEN_SECRET_FILE=/var/run/secrets/TOKEN_SECRET
      - DB_URI_FILE=/var/run/secrets/DB_URI
    depends_on:
      - db
    secrets:
      - TOKEN_SECRET
      - DB_URI


  # Production based database
  db:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME_FILE=/var/run/secrets/DB_ROOT_USER
      - MONGO_INITDB_ROOT_PASSWORD_FILE=/var/run/secrets/DB_ROOT_PASSWORD
      - MONGO_INITDB_USERNAME_FILE=/var/run/secrets/DB_USER
      - MONGO_INITDB_PASSWORD_FILE=/var/run/secrets/DB_PASSWORD
      - MONGO_INITDB_DATABASE_FILE=/var/run/secrets/DB_NAME
    ports:
      - '${DB_PORT}:27017'
    volumes:
      # Make data persist on local folder named ./mongo-volume
      - ${DB_DATA}:/data/db
      # Copy the database initialization script
      - ./.docker/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh 
        # Map mongo config file to /etc/mongo
      - ${DB_CONFIG}:/etc/mongo/
    # Specify config file
    command: ["-f", "/etc/mongo/mongod.conf"]
    # Credentials stored as secrets
    secrets:
      - DB_USER
      - DB_PASSWORD
      - DB_ROOT_USER
      - DB_ROOT_PASSWORD
      - DB_NAME

  # Api doc
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger_ui
    ports:
      - "${SWAGGER_PORT}:8080"
    volumes:
      - ${SWAGGER_DIR}:/usr/share/nginx/html/doc
    environment:
      API_URL: ${SWAGGER_API_URL}

  redoc:
    image: nginx
    container_name: 'api_redoc'
    ports:
      - "${REDOC_PORT}:80"
    volumes:
      - ${REDOC_SRC}:/usr/share/nginx/html
      - ${REDOC_CONF}:/etc/nginx/nginx.conf
