version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/home/user/app
    command: >
      sh -c "npm run dev"
    environment:
      - HOST=${HOST}
      - PORT=${PORT}
