name: Build and Test

on:
  push:
    branches: [ main, dev, deploy ]

jobs:

  app-dev:
    name: Build and test the app
    runs-on: ubuntu-latest
    env: 
      PORT: ${{ secrets.PORT }}
      HOST: ${{ secrets.HOST }}
      TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
      DB_ROOT_USER: ${{ secrets.DB_ROOT_USER }}
      DB_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_CONFIG: ${{ secrets.DB_CONFIG}}
      DB_INIT: ${{ secrets.DB_INIT }}
      DB_DATA: ${{ secrets.DB_CONFIG }}
      DB_URI: ${{ secrets.DB_URI }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build docker images 
        run: docker-compose -f docker-compose.dev.yml build --no-cache
      - name: Start containers 
        run: docker-compose -f docker-compose.dev.yml up -d app
      - name: Check running containers
        run: docker ps -a
      - name: Check logs of database
        run: docker logs mongodb
      - name: Run test
        run: docker exec bookish_node_dev sh -c "npm test && npm run lint"

