name: CI App Docker

on:
  push:
    branches: [ main ]

jobs:

  app-dev:
    name: Build and test the app
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build docker images and test the app
        env: 
          PORT: 8000
          HOST: 127.0.0.1
          TOKEN_SECRET: ${{ secrets.TOKEN_SECRET }}
          DB_ROOT_USER: devroot
          DB_ROOT_PASSWORD: devroot
          DB_USER: usertest
          DB_PASSWORD: passtest
          DB_NAME: bookishDBtest
          DB_PORT: 27017
          DB_HOST: 127.0.0.1
          DB_CONFIG: "./config/.docker"
          DB_INIT: "./config/.docker/docker-entrypoint-initdb.d/"
          DB_DATA: "./config/.docker/mongo-volume"
          DB_URI: "mongodb://usertest:passtest@127.0.0.1:8000/bookishDBtest"
          SWAGGER_PORT: 80
          SWAGGER_DIR: "./config/.swagger/"
          SWAGGER_API_URL: "doc/openapi_doc.yaml"
          REDOC_PORT: 8082
          REDOC_DIR: "./config/.redoc"
          REDOC_SRC: "./config/.redoc/src"
          REDOC_CONF: "./config/.redoc/config/nginx.conf"
        run: |
          echo 
          docker-compose -f docker-compose.dev.yml build --no-cache
          docker-compose -f docker-compose.dev.yml up
          docker-compose -f docker-compose.dev.yml run app sh -c "npm test"

